export const data = {
  users: [
    {
      id: 1,
      login: "jan.kowalski",
      password_hash: "hashed_password1",
      email: "jan.kowalski@example.com",
      phone: "+48123123123",
      first_name: "Jan",
      last_name: "Kowalski",
      preferred_test_drive_time: "09:00",
      created_at: "2024-01-01T10:00:00Z",
    },
    {
      id: 2,
      login: "anna.nowak",
      password_hash: "hashed_password2",
      email: "anna.nowak@example.com",
      phone: "+48234567890",
      first_name: "Anna",
      last_name: "Nowak",
      preferred_test_drive_time: "15:00",
      created_at: "2024-01-01T11:00:00Z",
    },
  ],
  cars: [
    {
      id: 1,
      image: '1',
      brand: "Toyota",
      model: "Corolla",
      price: 85000.0,
      body_type: "Sedan",
      power: 132,
      transmission: "Automatic",
      color: "White",
      production_year: 2023,
      description: "Compact car with great fuel economy.",
      details: {
        engine: "1.8L",
        features: ["Air Conditioning", "Bluetooth"],
      },
    },
    {
      id: 2,
      image: '2',
      brand: "BMW",
      model: "3 Series",
      price: 150000.0,
      body_type: "Sedan",
      power: 190,
      transmission: "Manual",
      color: "Black",
      production_year: 2022,
      description: "Luxury sedan with advanced features.",
      details: {
        engine: "2.0L",
        features: ["Leather seats", "Navigation"],
      },
    },
    {
      id: 3,
      image: '3',
      brand: "Tesla",
      model: "Model 3",
      price: 220000.0,
      body_type: "Sedan",
      power: 283,
      transmission: "Automatic",
      color: "Red",
      production_year: 2023,
      description: "Electric car with autopilot features.",
      details: {
        engine: "Electric",
        features: ["Autopilot", "Touchscreen"],
      },
    },
    {
      id: 4,
      image: '4',
      brand: "Ford",
      model: "Focus",
      price: 90000.0,
      body_type: "Hatchback",
      power: 150,
      transmission: "Automatic",
      color: "Blue",
      production_year: 2021,
      description: "Popular hatchback with modern features.",
      details: {
        engine: "1.5L",
        features: ["Cruise Control", "Backup Camera"],
      },
    },
    {
      id: 5,
      image: '5',
      brand: "Volkswagen",
      model: "Golf",
      price: 95000.0,
      body_type: "Hatchback",
      power: 140,
      transmission: "Manual",
      color: "Gray",
      production_year: 2023,
      description: "Compact and reliable hatchback.",
      details: {
        engine: "1.4L",
        features: ["Keyless Entry", "Park Assist"],
      },
    },
  ],
  test_drives: [
    {
      id: 1,
      user_id: 1,
      car_id: 1,
      test_drive_date: "2024-12-10",
      test_drive_time: "09:00",
      status: "scheduled",
    },
    {
      id: 2,
      user_id: 2,
      car_id: 2,
      test_drive_date: "2024-12-11",
      test_drive_time: "15:00",
      status: "scheduled",
    },
    {
      id: 3,
      user_id: 1,
      car_id: 3,
      test_drive_date: "2024-12-12",
      test_drive_time: "10:00",
      status: "scheduled",
    },
    {
      id: 4,
      user_id: 2,
      car_id: 4,
      test_drive_date: "2024-12-15",
      test_drive_time: "14:00",
      status: "completed",
    },
    {
      id: 5,
      user_id: 1,
      car_id: 5,
      test_drive_date: "2024-12-20",
      test_drive_time: "11:00",
      status: "scheduled",
    },
  ],
};